# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
#substitutions:
#  _SOMA_VERSION: 1
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
#  - '--build-arg'
#  - 'SOMA_VERSION=${_SOMA_VERSION}'
  - '-t'
  - 'gcr.io/$PROJECT_ID/go-soma-gcp:latest'
#  - '-t'
#  - 'gcr.io/$PROJECT_ID/go-soma-gcp:${_SOMA_VERSION}'
  - '.'
- name: 'gcr.io/$PROJECT_ID/go-soma-gcp'
  args: ['version']

images:
- 'gcr.io/$PROJECT_ID/go-soma-gcp:latest'
#- 'gcr.io/$PROJECT_ID/go-soma-gcp:${_SOMA_VERSION}'
tags: ['cloud-builders-community']
